### ISSUE TITLE
cborattr doesn't support of half float type

### ISSUE THREAD

**Issue by mibr0303** [apache/mynewt-mcumgr#107]
I have a tool that converts a JSON message into CBOR. When it converts a float into message to send to mcumgr it is handled by cborattr.c file except the message has the cbor type of CborHalfFloatType and that is currently not supported in the cborattr file system.
There is only the option to define the type in cborattr as CborAttrDoubleType or CborAttrFloatType. So when parsing the CBOR message with half float it will always fail in the following function:

static int valid_attr_type(CborType ct, CborAttrType at)
{
    switch (at) {
    case CborAttrIntegerType:
    case CborAttrUnsignedIntegerType:
        if (ct == CborIntegerType) {
            return 1;
        }
        break;
    case CborAttrByteStringType:
        if (ct == CborByteStringType) {
            return 1;
        }
        break;
    case CborAttrTextStringType:
        if (ct == CborTextStringType) {
            return 1;
        }
        break;
    case CborAttrBooleanType:
        if (ct == CborBooleanType) {
            return 1;
        }
               break;
#if FLOAT_SUPPORT
    case CborAttrFloatType:
        if (ct == CborFloatType) {
            return 1;
        }
        break;
    case CborAttrDoubleType:
        if (ct == CborDoubleType) {
            return 1;
        }
        break;
#endif
    case CborAttrArrayType:
        if (ct == CborArrayType) {
            return 1;
        }
        break;
    case CborAttrObjectType:
        if (ct == CborMapType) {
            return 1;
        }
        break;
    case CborAttrNullType:
        if (ct == CborNullType) {
            return 1;
        }
        break;
    default:
        break;
    }
    return 0;
}

**Comment by greg-leach** [comment]
https://github.com/apache/mynewt-mcumgr/pull/112 addresses this.

**Comment by greg-leach** [comment]
This issue can now be closed, https://github.com/apache/mynewt-mcumgr/pull/112 addresses this.

**Comment by utzig** [comment]
Fixed by #112, thanks!
