### ISSUE TITLE
fs mgmt not working under zephyr 2.5 

### ISSUE THREAD

**Issue by niclas-ats** [apache/mynewt-mcumgr#116]
It seems like the `fs_mgmt_impl_read` and `fs_mgmt_impl_write` functions are missing a proper initialization of the local `struct fs_file_t file` variable. The attached patch fixes the up-/download of files for me.

[0001-zephyr-fix-initialization-of-file-struct.txt](https://github.com/apache/mynewt-mcumgr/files/6022866/0001-zephyr-fix-initialization-of-file-struct.txt)

**Comment by de-nordic** [comment]
Can you post PR with the fix?

**Comment by niclas-ats** [comment]
Will this be picked up by https://github.com/zephyrproject-rtos/mcumgr as well? Or do I need to create a seperate pull request in that repo?

**Comment by de-nordic** [comment]
Yes, I will do the snapshot update.

**Comment by niclas-ats** [comment]
The fix didn't make it into yesterdays snapshot update. Once it's there I can test it and then close this issue.

**Comment by de-nordic** [comment]
> 
> 
> The fix didn't make it into yesterdays snapshot update. Once it's there I can test it and then close this issue.

Yes, it was little late to the party and the snapshot update has been already waiting for some time due to Zephyr release.

**Comment by niclas-ats** [comment]
Nevermind. I'll use my fork in the meantime. Thx for the quick approval!

**Comment by de-nordic** [comment]
Thanks!
