### ISSUE TITLE
Image transfer over uart not bootable

### ISSUE THREAD

**Issue by ErlendWithammerLux** [apache/mynewt-mcumgr#129]
Hello again! 
I'm working on transferring images to the nrf52840 by uploading it to nrf9160 and sending it over UART, on the nrf9160dk.

When the image has gone through the 91 it is not bootable however directly uploading it to the 52 works perfectly.
To see if there was a difference between the images I transferred the same image twice to the 52. The first way was using mcumgr upload image to the 52 and swapping it to slot 0, and the second way was transferring to 91 using the same command and then sending it over the uart to slot 1.

When calling mcuboot in the internal shell it lists both images, and they have the same size. Requesting an upgrade prints the error message of "image in slot 1 is not valid" when rebooted. 

Looking at the memory on the 52 gave these results which have some differences that might be the cause of the image being invalid.

![2021-06-25_11-55](https://user-images.githubusercontent.com/86069562/123411393-b3a7a180-d5b0-11eb-8d79-b0e6aecdc1d0.png)
![2021-06-25_12-02](https://user-images.githubusercontent.com/86069562/123411418-b904ec00-d5b0-11eb-859a-98e11f7434d9.png)

Another small problem is that only calling mcuboot in the internal shell lists the images, calling mcumgr image list only lists slot 0 after slot 1 being filled over uart. @de-nordic gave a posible reason for this here [https://github.com/apache/mynewt-mcumgr/issues/127](url) 

Thanks a lot for any help on this!

**Comment by de-nordic** [comment]
Can you share some more info regarding the image, like size and maybe 512 byes of header if that would not be a problem o security issue?

**Comment by ErlendWithammerLux** [comment]
Yes!
image header:
        Magic: 2532554813
        ih_load_addr: 0
        ih_hdr_size: 512
        _pad: 0
        ih_img_size: 178084
        ih_flags: 0
        iv_major: 0
        iv_minor: 0
        iv_revision: 0
        iv_build_num: 0
        pad_: 0
created packet: 0
(this is read form slot 1 on 91)

              
When requesting an upgrade the magic is good and swap type is set to test as it should.

Secondary image: magic=good, swap_type=0x2, copy_done=0x3, image_ok=0x3
I: Boot source: none
I: Swap type: test
E: Image in the secondary slot is not valid!

**Comment by de-nordic** [comment]
Are you sure that you are copying right image? The dumps you have shown contain irq vector tables but tables are different it does not seem to be any shift as other fields seem correct.
Can you sign your images adding versions to them and than share the first 512 bytes of bin file, the image headers?

**Comment by ErlendWithammerLux** [comment]
You seem to be correct indeed! 
hex of bin first 512 from 52:
in 
0000000 b83d 96f3 0000 0000 0200 0000 b8c4 0002
0000010 0000 0000 0000 0000 0000 0000 0000 0000
0000020 ffff ffff ffff ffff ffff ffff ffff ffff
*
0000200

hex of bin first 512 from 91:
n 
0000000 b83d 96f3 0000 0000 0200 0000 4ad4 0003
0000010 0000 0000 0000 0000 0000 0000 0000 0000
0000020 ffff ffff ffff ffff ffff ffff ffff ffff
*
0000200

Looking at JMemExe this is identical (not quite to the dumps as i have slightly changed the images).
So JMemExe is only reading the nrf9160dk_nrf9160s memory not the 52 so the dumps are indeed wrong.

I will look into reading the rigth memory further. 

I am not 100% sure I'm copying the right image. I use img_mgmt_impl_read(1,sent,&data,to_send) to copy it.
The sizes of img91 and img52 are very different, therefore since the read header size is the size of img52 it does seem like the right image is copied.

**Comment by de-nordic** [comment]
I guess you have nrf9120 dev board,  can switch the debug interface (SW10) to nrf52840? you  should be able to use nrfjprog tool to dump the memory to binary file.

**Comment by ErlendWithammerLux** [comment]
hexdump slot0.bin 
0000000 b83d 96f3 0000 0000 0200 0000 b8c4 0002
0000010 0000 0000 0000 0000 0000 0000 0000 0000
0000020 ffff ffff ffff ffff ffff ffff ffff ffff
*
0000200

hexdump slot1.bin 
0000000 b83d 96f3 0000 0000 0200 0000 b8c4 0002
0000010 0000 0000 0000 0000 0000 0000 0000 0000
0000020 ffff ffff ffff ffff ffff ffff ffff ffff
*
0000200

both from the 52

**Comment by de-nordic** [comment]
And they both match the one you are uploading via uart?

**Comment by ErlendWithammerLux** [comment]
Yes, i now took a look at the whole first and second slot and they are identical in both the beginning and the end so probably all over

**Comment by de-nordic** [comment]
Good seems the uart transfer is fine, so we have this out of the way.

**Comment by ErlendWithammerLux** [comment]
Is there some sort of flags or termination characters that are being set when uploading through the mcumgr-cli to validate the image?

**Comment by ErlendWithammerLux** [comment]
Got it to work!

Was missing the tlv which was causing the image to be invalid.

Thanks a lot for the help!

**Comment by de-nordic** [comment]
Yes. That was supposed to be my next question: whether you confirm the image on the device you upload it to.
The mcumgr does not do that by default, unless the image has been marked as confirmed with imgtool.
The receiving application, on the second mcu, should set the new application it received for test, or confirmed pending; in case when the application will be set for test it needs to confirm itself after reboot (and probably some internal tests).
You may use functions from zephyr/subsys/dfu/boot/mcuboot.c to confirm at run-time.

**Comment by de-nordic** [comment]
@ErlendWithammerLux please close the issue if it is no longer relevant. Thanks!
