### ISSUE TITLE
Image upload callback seems to be wrong

### ISSUE THREAD

**Issue by lairdjm** [apache/mynewt-mcumgr#136]
There are 3 defined status codes for the image upload callback:
```
IMG_MGMT_ID_UPLOAD_STATUS_START
IMG_MGMT_ID_UPLOAD_STATUS_ONGOING
IMG_MGMT_ID_UPLOAD_STATUS_COMPLETE
```
However it seems only START and ONGOING are used. Start doesn't actually indicate a start, it indicates everything except the final part, and the final part is indicated with the ongoing status, complete is actually never used and is only in the code as a define, no .c files reference it.

**Comment by alokprinc** [comment]
I m a beginner but can I work on this issue.
It will be a great opportunity for learning

**Comment by lairdjm** [comment]
@alokprinc It's already fixed in the linked pull request

**Comment by alokprinc** [comment]
I want to start contributing can you please allow me to work.
I am comfortable with java, c++.
