### ISSUE TITLE
Installation Instructions out of date

### ISSUE THREAD

**Issue by scath999** [apache/mynewt-mcumgr#166]
The current installation instructions appear to be out of date.

`$ go get github.com/apache/mynewt-mcumgr-cli/mcumgr`

Issuing that command renders the following on Win10:
```
go: go.mod file not found in current directory or any parent directory.
        'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
```

The proper installation command (at least for win) is now

`go install github.com/apache/mynewt-mcumgr-cli/mcumgr@latest`

Please consider updating.

**Comment by sjanc** [comment]
Fixed in https://github.com/apache/mynewt-mcumgr/pull/169
