### ISSUE TITLE
Unable to compile sample on zephyr 1.11

### ISSUE THREAD

**Issue by yatishmishra** [apache/mynewt-mcumgr#3]
Hi I am using zephyr 1.11 and trying to compile the sample code. I am getting following errors
FAILED: ccache /home/yatish/zephyr-sdk-0.9.2/sysroots/x86_64-pokysdk-linux/usr/bin/arm-zephyr-eabi/arm-zephyr-eabi-gcc -DKERNEL -DMBEDTLS_CONFIG_FILE=\"config-mini-tls1_2.h\" -DNRF52840_XXAA -D_FORTIFY_SOURCE=2 -D__ZEPHYR__=1 -I/home/yatish/Desktop/zephyr-zephyr-v1.11.0/kernel/include -I/home/yatish/Desktop/zephyr-zephyr-v1.11.0/arch/arm/include -I/home/yatish/Desktop/zephyr-zephyr-v1.11.0/arch/arm/soc/nordic_nrf5/nrf52 -I/home/yatish/Desktop/zephyr-zephyr-v1.11.0/arch/arm/soc/nordic_nrf5/nrf52/include -I/home/yatish/Desktop/zephyr-zephyr-v1.11.0/arch/arm/soc/nordic_nrf5/include -I/home/yatish/Desktop/zephyr-zephyr-v1.11.0/boards/arm/nrf52840_pca10056 -I/home/yatish/Desktop/zephyr-zephyr-v1.11.0/include -I/home/yatish/Desktop/zephyr-zephyr-v1.11.0/include/drivers -Izephyr/include/generated -isystem /home/yatish/zephyr-sdk-0.9.2/sysroots/x86_64-pokysdk-linux/usr/lib/arm-zephyr-eabi/gcc/arm-zephyr-eabi/6.2.0/include -isystem /home/yatish/zephyr-sdk-0.9.2/sysroots/x86_64-pokysdk-linux/usr/lib/arm-zephyr-eabi/gcc/arm-zephyr-eabi/6.2.0/include-fixed -I/home/yatish/zephyr-sdk-0.9.2/sysroots/armv5-zephyr-eabi/usr/include -I/home/yatish/Desktop/zephyr-zephyr-v1.11.0/ext/lib/crypto/tinycrypt/include -I/home/yatish/Desktop/zephyr-zephyr-v1.11.0/ext/hal/cmsis/Include -I/home/yatish/Desktop/zephyr-zephyr-v1.11.0/ext/hal/nordic/nrfx -I/home/yatish/Desktop/zephyr-zephyr-v1.11.0/ext/hal/nordic/nrfx/drivers/include -I/home/yatish/Desktop/zephyr-zephyr-v1.11.0/ext/hal/nordic/nrfx/hal -I/home/yatish/Desktop/zephyr-zephyr-v1.11.0/ext/hal/nordic/nrfx/mdk -I/home/yatish/Desktop/zephyr-zephyr-v1.11.0/ext/hal/nordic/. -I/home/yatish/Desktop/zephyr-zephyr-v1.11.0/subsys/bluetooth -I/home/yatish/Desktop/zephyr-zephyr-v1.11.0/ext/fs/nffs/include -I/home/yatish/Desktop/zephyr-zephyr-v1.11.0/ext/lib/crypto/mbedtls/include -I/home/yatish/Desktop/zephyr-zephyr-v1.11.0/ext/lib/crypto/mbedtls/configs -I/home/yatish/Desktop/zephyr-zephyr-v1.11.0/ext/lib/mgmt/mcumgr/cborattr/include -I/home/yatish/Desktop/zephyr-zephyr-v1.11.0/ext/lib/mgmt/mcumgr/cmd/fs_mgmt/include -I/home/yatish/Desktop/zephyr-zephyr-v1.11.0/ext/lib/mgmt/mcumgr/cmd/img_mgmt/include -I/home/yatish/Desktop/zephyr-zephyr-v1.11.0/ext/lib/mgmt/mcumgr/cmd/os_mgmt/include -I/home/yatish/Desktop/zephyr-zephyr-v1.11.0/ext/lib/mgmt/mcumgr/cmd/stat_mgmt/include -I/home/yatish/Desktop/zephyr-zephyr-v1.11.0/ext/lib/mgmt/mcumgr/mgmt/include -I/home/yatish/Desktop/zephyr-zephyr-v1.11.0/ext/lib/mgmt/mcumgr/mgmt/port/zephyr/include -I/home/yatish/Desktop/zephyr-zephyr-v1.11.0/ext/lib/mgmt/mcumgr/smp/include -I/home/yatish/Desktop/zephyr-zephyr-v1.11.0/ext/lib/mgmt/mcumgr/util/include -I/home/yatish/Desktop/zephyr-zephyr-v1.11.0/ext/lib/encoding/tinycbor/src -Os -g -Wall -Wformat -Wformat-security -Wno-format-zero-length -imacros /home/yatish/Desktop/zephyr-zephyr-v1.11.0/samples/mynewt-mcumgr-master/samples/smp_svr/zephyr/build/zephyr/include/generated/autoconf.h -ffreestanding -Wno-main -std=c99 -fno-asynchronous-unwind-tables -fno-pie -fno-pic -fno-strict-overflow -Wno-pointer-sign -Wno-unused-but-set-variable -fno-reorder-functions -fno-defer-pop -Werror=implicit-int -ffunction-sections -fdata-sections -mabi=aapcs --sysroot /home/yatish/zephyr-sdk-0.9.2/sysroots/armv5-zephyr-eabi/usr -mthumb -mcpu=cortex-m4 -MD -MT CMakeFiles/app.dir/src/main.c.obj -MF CMakeFiles/app.dir/src/main.c.obj.d -o CMakeFiles/app.dir/src/main.c.obj   -c ../src/main.c
In file included from /home/yatish/Desktop/zephyr-zephyr-v1.11.0/include/fs/nffs_fs.h:11:0,
                 from /home/yatish/Desktop/zephyr-zephyr-v1.11.0/include/fs/fs_interface.h:47,
                 from /home/yatish/Desktop/zephyr-zephyr-v1.11.0/include/fs.h:11,
                 from ../src/main.c:20:
/home/yatish/Desktop/zephyr-zephyr-v1.11.0/ext/fs/nffs/include/nffs/nffs.h:530:0: warning: "STATS_INC" redefined
 #define STATS_INC(sectvarname, var)
 
In file included from ../src/main.c:14:0:
/home/yatish/Desktop/zephyr-zephyr-v1.11.0/include/stats.h:155:0: note: this is the location of the previous definition
 #define STATS_INC(group__, var__) \
 
../src/main.c:52:15: error: variable ‘nffs_mnt’ has initializer but incomplete type
 static struct fs_mount_t nffs_mnt = {
               ^~~~~~~~~~
../src/main.c:53:2: error: unknown field ‘type’ specified in initializer
  .type = FS_NFFS,
  ^
../src/main.c:53:10: error: ‘FS_NFFS’ undeclared here (not in a function)
  .type = FS_NFFS,
          ^~~~~~~
../src/main.c:53:10: warning: excess elements in struct initializer
../src/main.c:53:10: note: (near initialization for ‘nffs_mnt’)
../src/main.c:54:2: error: unknown field ‘mnt_point’ specified in initializer
  .mnt_point = "/nffs",
  ^
../src/main.c:54:15: warning: excess elements in struct initializer
  .mnt_point = "/nffs",
               ^~~~~~~
../src/main.c:54:15: note: (near initialization for ‘nffs_mnt’)
../src/main.c:55:2: error: unknown field ‘fs_data’ specified in initializer
  .fs_data = &flash_desc,
  ^
../src/main.c:55:13: warning: excess elements in struct initializer
  .fs_data = &flash_desc,
             ^
../src/main.c:55:13: note: (near initialization for ‘nffs_mnt’)
../src/main.c: In function ‘main’:
../src/main.c:133:3: error: invalid use of undefined type ‘struct fs_mount_t’
   nffs_mnt.storage_dev = flash_dev;
   ^~~~~~~~
../src/main.c:135:8: warning: implicit declaration of function ‘fs_mount’ [-Wimplicit-function-declaration]
   rc = fs_mount(&nffs_mnt);
        ^~~~~~~~
../src/main.c: At top level:
../src/main.c:52:26: error: storage size of ‘nffs_mnt’ isn’t known
 static struct fs_mount_t nffs_mnt = {
                          ^~~~~~~~
[28/248] Building C object zephyr/CMakeFiles/zephyr.dir/arch/arm/core/cortex_m/prep_c.c.obj
ninja: build stopped: subcommand failed.

**Comment by nvlsianpu** [comment]
Hi - Your compilation failed on lack of multi-fs support we had added to the zephyr-project master (wasn't available for 1.11 release, see https://github.com/zephyrproject-rtos/zephyr/pull/6318). Zephyr-project contain compatible verison of FS subsystems and mcumgr. If you want to use the newest <b>mcumgr</b> - you have to use newest zephyr master branch.

**Comment by carlescufi** [comment]
@ccollins476ad this seems to be obsolete, mind closing it?
