### ISSUE TITLE
Bug: Can't get and install mcumgr

### ISSUE THREAD

**Issue by zarnobarintive** [apache/mynewt-mcumgr#64]
I tried to follow guides from README file and install mcumgr but without success. I'm using ubuntu 18.04  here is output from console:

```
 go get github.com/apache/mynewt-mcumgr-cli/mcumgr
# mynewt.apache.org/newt/util
../../../go/src/mynewt.apache.org/newt/util/util.go:477:10: state.ExitCode undefined (type *os.ProcessState has no field or method ExitCode)
../../../go/src/mynewt.apache.org/newt/util/util.go:480:17: state.ExitCode undefined (type *os.ProcessState has no field or method ExitCode)
```
my go version is

```
go version
go version go1.10.4 linux/amd64
```
I also tried to ```export GO111MODULE=on``` but it doesn't change output.

**Comment by utzig** [comment]
You need at least go 1.12. The go developers provide a PPA: https://github.com/golang/go/wiki/Ubuntu

**Comment by zarnobarintive** [comment]
Looks like it helped. Thanks.
